---
version: "3"

env:
  CGO_ENABLED: 0

tasks:
  client:
    summary: Runs outbox client app
    cmds:
      - task: deps-up
      - task: _start_client

  worker:
    summary: Runs outbox worker app
    cmds:
      - task: deps-up
      - task: _start_worker

  _start_client:
    summary: Starts client app, expects all deps to be available
    cmds:
      - go run ./... client
    env:
      DB_DSN: "postgres://outbox:outbox@localhost:{{.PG_PORT}}/outbox?sslmode=disable"
    vars:
      PG_PORT:
        # `docker compose port postgres 5432` -> "0.0.0.0:52041"
        sh: docker compose port postgres 5432 | cut -f2 -d":"

  _start_worker:
    summary: Starts worker app, expects all deps to be available
    cmds:
      - go run ./... worker
    env:
      DB_DSN: "postgres://outbox:outbox@localhost:{{.PG_PORT}}/outbox?sslmode=disable"
      KAFKA_BROKERS: "localhost:{{.KAFKA_PORT}}"
    vars:
      PG_PORT:
        # `docker compose port postgres 5432` -> "0.0.0.0:52041"
        sh: docker compose port postgres 5432 | cut -f2 -d":"
      KAFKA_PORT:
        # `docker compose port redpanda 9092` -> "0.0.0.0:65027"
        sh: docker compose port redpanda 9092 | cut -f2 -d":"

  deps-up:
    summary: Starts test dependencies
    cmds:
      - cmd: docker compose up --detach --wait

  deps-down:
    summary: Stops test dependencies
    cmds:
      - cmd: docker compose down -v
